---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-smb-cloning
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: smb
  dataSource:
    kind: PersistentVolumeClaim
    name: pvc-smb
